# Generated by Django 5.2.17 on 2026-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("safepay", "Safepay")],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
