# Generated by Django 5.2.17 on 2026-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("pkr", "PKR"), ("usd", "USD")], default="pkr", max_length=3
            ),
        ),
    ]
