# Generated by Django 5.2.17 on 2026-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customer_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
