# Generated by Django 5.2.17 on 2026-09-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_spots", "0003_alter_parkingspot_spot_type"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="parking_spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spot_tickets",
                to="parking_spots.parkingspot",
            ),
        ),
    ]
